### ISSUE TITLE
originalTilePoint.scaleBy is not a function

### ISSUE THREAD

**Issue by Brendan92** [mapbox/leaflet-image#96]
I'm not sure where my problem is, but I keep on getting this error: 

TypeError: originalTilePoint.scaleBy is not a function
    at http://***/leaflet-image/leaflet-image.js:119:18
    at Array.forEach (native)
    at handleTileLayer (http://***/leaflet-image/leaflet-image.js:111:15)
    at start (http://***/leaflet-image/leaflet-image.js:335:13)
    at poke (http://***/leaflet-image/leaflet-image.js:323:26)
    at Queue.defer (http://***/leaflet-image/leaflet-image.js:301:7)
    at drawTileLayer (http://***/leaflet-image/leaflet-image.js:45:50)
    at eachLayer (http://***/leaflet/dist/leaflet.js:6:21728)
    at leafletImage (http://***/leaflet-image/leaflet-image.js:32:9)

Can someone assist me on what I'm doing wrong or is this a fault with the plugin?

**Comment by aanil649** [comment]
Encountering same error. Any fix to this problem.

**Comment by KimaniKihiu** [comment]
Any solution to this?

**Comment by anotheredward** [comment]
Fixed by reverting to v0.3.0 as it doesn't use "scaleBy". Not ideal, but works.

**Comment by tombrennan06** [comment]
scaleBy is in Leaflet 1.0, but not 0.7. You're presumably using the older version. You'll need to upgrade, or alternatively edit the current version of leaflet-image to work around. This might work:

```
var tilePos = originalTilePoint
.multiplyBy(tileSize)
.subtract(bounds.min);
```

**Comment by tombrennan06** [comment]
You can just upgrade to Leaflet 1.0. Or if you can't upgrade, use the code workaround above. It's not an issue with the plugin that needs resolving.
